services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookflow_sqlserver
    user: "0:0"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data
    networks:
      - bookflow-network

  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    container_name: bookflow_ai_service
    ports:
      - "8000:8000"
    volumes:
      - ./ai_service:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - bookflow-network

  webapi:
    image: bookflow-api
    container_name: bookflow_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=BookFlowDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;MultipleActiveResultSets=true
      - AiService__BaseUrl=http://ai_service:8000
    depends_on:
      - sqlserver
      - ai_service
    networks:
      - bookflow-network

volumes:
  sqlserver_data:

networks:
  bookflow-network:
    driver: bridge